name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
      - name: Set up Java and GitHub Packages
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Test
        run: ./mvnw verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package to GitHub Packages
        run: ./mvnw deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
