name: Publish release to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java and GitHub Packages
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Extract Tag Name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF##*/})"
        id: extract_tag
      - name: Set version package
        run: mvn versions:set -DnewVersion=${{ steps.extract_tag.outputs.tag }}
      - name: Publish package to GitHub Packages
        run: mvn -Dchangelist= deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
